/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the full intelligence pipeline and return a structured result */
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch previously persisted analyses for a set of log IDs */
        post: operations["queryAnalyses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove the persisted analysis for a single log */
        delete: operations["deleteAnalysis"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove all persisted analyses that are tied to a log */
        delete: operations["deleteAllAnalyses"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create/index a document for retrieval (RAG) */
        post: operations["createRagDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a previously indexed RAG document */
        delete: operations["deleteRagDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/delete_all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove all documents from the RAG retrieval store */
        delete: operations["deleteAllRagDocuments"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search the retrieval store for relevant documents */
        post: operations["searchRag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the historical deployment timeline */
        get: operations["getDeploymentHistory"];
        put?: never;
        /**
         * Ingest a deployment log event
         * @description Accepts a deployment log event and publishes it asynchronously via RabbitMQ for processing
         */
        post: operations["ingestLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve deployment logs matching a given list of UUIDs */
        get: operations["getLogsByIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a list of incident statuses, optionally filtered by status */
        get: operations["getIncidentStatuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{logId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the status of a specific incident */
        patch: operations["updateStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example py-intelligence */
            service: string;
        };
        AnalyzeRequest: {
            /** @description Raw log/text content to analyze. */
            content: string;
            /**
             * @description Which inference mode to use.
             * @default local
             * @enum {string}
             */
            mode: "local" | "cloud";
            /** @default false */
            use_rag: boolean;
            /** @description Optional additional context from the caller. */
            context?: string | null;
            /** @description Log this analysis belongs to, if any. When set, the result is persisted and retrievable via /api/v1/analyses/query. */
            log_id?: string | null;
        };
        AnalyzeResponse: {
            /**
             * @description UI tag/category of the detected problem.
             * @example database_timeout
             */
            problem_type: string;
            /**
             * @description Detected severity of the problem.
             * @example Medium
             */
            severity: string;
            /** @description Short overall summary. */
            summary: string;
            /** @description What went wrong / main issue. */
            problem_summary: string;
            /** @description Evidence / hints parsed from logs. */
            evidence: string[];
            /** @description Recommended troubleshooting/diagnostic steps. */
            troubleshoot: string[];
            /** @description Suggested fixes / next steps. */
            solutions: string[];
            /** @description Optional references used for RAG. */
            sources?: components["schemas"]["SourceRef"][];
            /**
             * @description Confidence level of the analysis.
             * @example Medium
             */
            confidence: string;
        };
        AnalysesQueryRequest: {
            /** @description Log IDs to fetch persisted analyses for. */
            log_ids: string[];
        };
        /** @description Map of log_id to its persisted analysis. Log IDs with no stored analysis are omitted. */
        AnalysesQueryResponse: {
            [key: string]: components["schemas"]["AnalyzeResponse"];
        };
        SourceRef: {
            /** @description Source identifier (e.g., document id). */
            id: string;
            title?: string;
            url?: string;
        };
        CreateRagDocumentRequest: {
            title: string;
            content: string;
            /** @default [] */
            tags: string[];
        };
        RagDocument: {
            id: string;
            title: string;
            content: string;
            tags: string[];
        };
        RagSearchRequest: {
            query: string;
            /** @default 5 */
            limit: number;
        };
        RagSearchResponse: {
            results: components["schemas"]["RagSearchResult"][];
            count: number;
        };
        RagSearchResult: {
            document_id: string;
            title: string;
            /** Format: float */
            score: number;
            snippet: string;
        };
        ErrorDetail: {
            detail: string;
        };
        IncomingLogEventDto: {
            /**
             * @description Name of the service that generated the deployment log
             * @example auth-service
             */
            serviceName: string;
            /** @description Raw deployment log content to be ingested */
            logContent: string;
            /**
             * Format: date-time
             * @description Optional timestamp of when the log was generated
             */
            timestamp?: string | null;
            /**
             * @description Log severity level
             * @default INFO
             * @enum {string}
             */
            severity: "INFO" | "WARNING" | "ERROR" | "CRITICAL";
            /** @description Optional key-value metadata associated with the deployment */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** @description Representation of a log entity from the logbook service */
        Log: {
            /** Format: uuid */
            id?: string;
            serviceName?: string;
            logContent?: string;
            /** Format: date-time */
            timestamp?: string;
            severity?: string;
        };
        /** @description Represents the status of a parsed incident log */
        IncidentStatus: {
            /** Format: uuid */
            logId?: string;
            /** @example ACTIVE */
            status?: string;
        };
        StatusUpdateDto: {
            /** @example RESOLVED */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Structured analysis result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    queryAnalyses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysesQueryRequest"];
            };
        };
        responses: {
            /** @description Map of log_id to persisted analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysesQueryResponse"];
                };
            };
        };
    };
    deleteAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAllAnalyses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All persisted analyses deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRagDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRagDocumentRequest"];
            };
        };
        responses: {
            /** @description Document accepted for indexing */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagDocument"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    deleteRagDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    deleteAllRagDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All documents deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    searchRag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagSearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagSearchResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    getDeploymentHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of historical deployment logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Log"][];
                };
            };
        };
    };
    ingestLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomingLogEventDto"];
            };
        };
        responses: {
            /** @description Log event accepted for asynchronous processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLogsByIds: {
        parameters: {
            query: {
                ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered list of logs by IDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Log"][];
                };
            };
        };
    };
    getIncidentStatuses: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of incidents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentStatus"][];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdateDto"];
            };
        };
        responses: {
            /** @description Status successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Incident status not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
