package org.devpulse.logbook.entity;

import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "deployment_logs")
public class DeploymentLog {

    @Id
    private UUID logId; // Uses the UUID generated by spring-ingestion!

    @Column(nullable = false)
    private String serviceName;

    @Column(nullable = false)
    private String environment;

    @Column(nullable = false)
    private String severity;

    @Column(columnDefinition = "TEXT")
    private String logContent;

    @Column(nullable = false)
    private Instant timestamp;

    // Required empty constructor for JPA
    public DeploymentLog() {
    }

    // Updated constructor to require the UUID
    public DeploymentLog(UUID logId, String serviceName, String environment, String severity, String logContent, Instant timestamp) {
        this.logId = logId;
        this.serviceName = serviceName;
        this.environment = environment;
        this.severity = severity;
        this.logContent = logContent;
        this.timestamp = timestamp;
    }

    // --- Getters ---
    public UUID getLogId() {
        return logId;
    }

    public String getServiceName() {
        return serviceName;
    }

    public String getEnvironment() {
        return environment;
    }

    public String getSeverity() {
        return severity;
    }

    public String getLogContent() {
        return logContent;
    }

    public Instant getTimestamp() {
        return timestamp;
    }
}
